# https://taskfile.dev
# go install github.com/go-task/task/v3/cmd/task@latest
version: '3'

vars:
  VERSION: 0.1.2a
  APPLICATION_VERSION: -X 'main.APPLICATION_VERSION={{.VERSION}}'
  BUILD_FLAGS: -ldflags "-s -w {{.APPLICATION_VERSION}}"
  PACKAGES: ./cmd/protocol/.

includes:
  build: 
    taskfile: Taskfile_{{OS}}.yml
    vars:
      GLOBAL_OPTIONS: "{{.BUILD_FLAGS}} {{.PACKAGES}}"      

tasks:
  default:
    deps: 
      - build:default